Refactored password entry, and added pinentry password entry Doesn't work for entering new passwords yet, though

diff --git a/slimpass b/slimpass
--- a/slimpass
+++ b/slimpass
@@ -22,12 +22,31 @@ canonicalize() {
   echo $RESULT
 }
 
+# Password query functions
+sp_osxkeychain() {
+  SECURITY_RESULT=$(security 2>&1 >/dev/null find-generic-password -ga slimpass)
+  echo $SECURITY_RESULT | sed "s/^password: \"\([^\"]*\)\"$/\\1/g"
+}
+
+sp_pinentry() {
+  PINENTRY_RESULT=$((echo SETPROMPT $1 ; echo GETPIN) | pinentry 2>/dev/null)
+  echo -n "$PINENTRY_RESULT" | grep '^ERR ' >/dev/null 2>&1 && return 1
+  echo -n "$PINENTRY_RESULT" | grep '^D ' |cut -d" " -f2
+}
+
+sp_read() {
+  read -s -p "$1 " PASSWORD_TMP
+  echo >&2
+  echo $PASSWORD_TMP
+}
+
 PASSWORD_FILE="$HOME/.passwords"
 NAME=
 OPERATION=query
 ARGS_PROCESSED=0
+PASSWORD_METHOD=read
 
-while getopts "adcln:r:K" OPTION
+while getopts "adcln:r:K:" OPTION
 do
   case $OPTION in
   a)
@@ -52,13 +71,8 @@ do
     ARGS_PROCESSED=$(($ARGS_PROCESSED + 1))
     ;;
   K)
-    SECURITY_RESULT=$(security 2>&1 >/dev/null find-generic-password -ga slimpass)
-    if [ $? -ne 0 ]
-    then
-      echo "slimpass entry was not present in Mac OS X login keychain" >&2
-      exit 4
-    fi
-    PASSWORD_FILE_PASSWORD=$(echo $SECURITY_RESULT | sed "s/^password: \"\([^\"]*\)\"$/\\1/g")
+    PASSWORD_METHOD="$OPTARG"
+    ARGS_PROCESSED=$(($ARGS_PROCESSED + 1))
     ;;
   *)
     ARGS_PROCESSED=$(($ARGS_PROCESSED - 1))
@@ -80,10 +94,11 @@ fi
 
 PASSWORD_FILE=$(canonicalize $PASSWORD_FILE)
 
-if [ -z "$PASSWORD_FILE_PASSWORD" ]
+PASSWORD_FILE_PASSWORD=$(sp_$PASSWORD_METHOD "Enter password file password:")
+if [ $? -ne 0 ]
 then
-  read -s -p "Enter password file password: " PASSWORD_FILE_PASSWORD
-  echo >&2
+  echo "Password could not be retrieved" >&2
+  exit 4
 fi
 export PASSWORD_FILE_PASSWORD
 
@@ -103,8 +118,13 @@ create)
     echo "Password file $PASSWORD_FILE already exists - remove first to create" >&2
     exit 2
   fi
-  read -s -p "Verify password file password: " PASSWORD_FILE_PASSWORD2
-  echo
+  PASSWORD_FILE_PASSWORD2=$(sp_$PASSWORD_METHOD "Verify password file password:")
+  if [ $? -ne 0 ]
+  then
+    echo "Password could not be retrieved" >&2
+    exit 4
+  fi
+  echo >&2
   if [ $PASSWORD_FILE_PASSWORD != $PASSWORD_FILE_PASSWORD2 ]
   then
     echo "Passwords do not match - please retry" >&2
